import { Provider } from "@/components/shared/provider";
import "@/styles/globals.css";
import { Montserrat_Alternates } from "next/font/google";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const montserratAlternates = Montserrat_Alternates({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  variable: "--font-montserrat-alternates",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={montserratAlternates.className}>
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <main className="min-h-screen" role="main">
          {/* header */}
          {/* auth layout */}
          <Provider>{children}</Provider>
          {/* footer */}
        </main>
      </body>
    </html>
  );
}
